config/routes.rb
MembershipProfilesSample::Application.routes.draw do

  match 'user_interest/:uid/new' => 'user_interests#new', :as => :new_user_interest, :via => :get
  match 'user_interest/:uid/save' => 'user_interests#save', :as => :save_user_interest, :via => :post

  devise_for :users, :controllers => {:registrations => "registrations"}

	resources :users, :only => [:index] do
    collection do
      get 'search'
    end
  end
  
  match 'users/:id/show' => 'users#show', :as => :user, :via => :get
  match 'users/:id/edit' => 'users#edit', :as => :edit_user, :via => :get
	match 'users/:id/update' => 'users#update', :as => :update_user, :via => :put
  

  root :to => 'users#index'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :user_interests
	has_many :users, :through => :user_interests
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable,:recoverable
  devise :database_authenticatable, :registerable,
		:rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
    	
	attr_accessible :email, :password, :password_confirmation, 
		:remember_me, :avatar, :name, :location_country, :location_city
  # attr_accessible :title, :body

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

	validates_attachment :avatar, :presence => true,
		:content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :name, :location_country, :presence => true

	has_many :user_interests
	has_many :interests, :through => :user_interests
	
  def self.search_result q
	return [] if q.blank?
	where("name like (?) OR email like (?)", "%#{q.split(' ').first}%", "%#{q.split(' ').first}%")
  end
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
	belongs_to :user
	belongs_to :interest
  attr_accessible :interest_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :parse_params, :only => [ :create ]
  
  def create
    super
  end
  
  private
  def parse_params
    params["user"]["location_country"] = JSON.parse(params["user"]["location_country"]).first rescue nil
  end
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
  def new
		@user = User.find(params[:uid])
		@interests = Interest.all.map(&:name).join(", ")
  end

  def save
		@user = User.find(params[:uid])
		interests = JSON.parse(params["user_interest"]) rescue []
		interests.each do |i_name|
			interest = Interest.find_or_create_by_name(i_name)
			UserInterest.find_or_create_by_user_id_and_interest_id(@user.id, interest.id)
		end
    respond_to do |format|
      if @user.save
				uintrests = @user.interests
				extra_uis = uintrests.map(&:name) - interests
				extra_uis.each do |ui_name| 
          _interest = Interest.select('id').where(:name => ui_name).first
          UserInterest.find_by_user_id_and_interest_id(@user.id, _interest.id).destroy if _interest.present?
        end
        format.html { redirect_to @user, notice: 'User interest was successfully saved.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	before_filter :parse_params, :only => [ :search ]
	before_filter :parse_country_params, :only => [ :update ]
	before_filter { flash[:alert] = nil }

  # GET /users
  # GET /users.json
  def index
    @users = User.all
	
		flash[:alert] =  @users.blank? ? "Sorry, There are no members yet!" : nil
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1/show
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
  # GET /users/search
  def search
    @users = User.search_result(params[:q])
    flash[:alert] = "No result found for this filter!" if @users.blank?
		render "index"
  end

#  # GET /users/new
#  # GET /users/new.json
#  def new
#    @user = User.new

#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @user }
#    end
#  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

#  # POST /users
#  # POST /users.json
#  def create
#    @user = User.new(params[:user])

#    respond_to do |format|
#      if @user.save
#        format.html { redirect_to @user, notice: 'User was successfully created.' }
#        format.json { render json: @user, status: :created, location: @user }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # PUT /users/1/update
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

#  # DELETE /users/1
#  # DELETE /users/1.json
#  def destroy
#    @user = User.find(params[:id])
#    @user.destroy

#    respond_to do |format|
#      format.html { redirect_to users_url }
#      format.json { head :no_content }
#    end
#  end

  private
  def parse_params
    params["q"] = JSON.parse(params["q"]).first rescue nil
  end

  def parse_country_params
    params["user"]["location_country"] = JSON.parse(params["user"]["location_country"]).first rescue nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembershipProfilesSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<% if user_signed_in? %>	
	<div class="row AL-signout MS-search">
		<div class="span6 search-wraper">
			<%= form_tag(search_users_path, :method => "get") do %>
			  <div id="search_text"></div>
			  <%= submit_tag("Search", :class => "btn search") %>
			<% end %>
		</div>
		<div class="span5 AL-navbar-links">
			<%= link_to "home", root_path %> | 
			<%= link_to "my-profile", user_path(current_user) %> | 
			<%= link_to "my-interest", new_user_interest_path(current_user.id) %> | 
			<%= link_to "sign-out", destroy_user_session_path, :method => :delete %>
		</div>
	</div>
	<% if flash[:alert] %>
	<div class="alert alert-info">
		<%= flash[:alert] %>
	<div>
	<% end %>
	<% end %>
	<%= yield %>
</div>

<script>
 $(function() {
    $("#search_text" ).magicSuggest({
        id: 'search_text',
        name: 'q',
        class: 'search-query',
	    allowFreeEntries: false,
        data: "<%=User.all.map(&:name).join(', ')%>",
        value: '["<%=params["q"]%>"]',
		maxDropHeightinteger: 120,
		maxSelection: 1,
		hideTrigger: true
    });
  });
</script>

</body>
</html>

app/views/user_interests/new.html.erb
<%= form_tag(save_user_interest_path(@user.id), :method => "post") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset class="">
		<legend>Choose your Interests</legend>

		<label for"user_interest">User interest</label>
		<div id="user_interest"></div>
		
		<% if current_user.id == @user.id %>
    	<%= submit_tag "Save", :class => "btn display-block" %>
		<% end %>
	</fieldset>
<% end %>

<script>
 $(function() {
    $("#user_interest" ).magicSuggest({
        id: 'user_interest',
        name: 'user_interest',
        data: "<%=@interests%>",
				maxDropHeightinteger: 120,
        value: '["<%=@user.interests.map(&:name).join('","').html_safe%>"]',
				maxSelection: null
    });
  });
</script>

app/views/user_interests/save.html.erb
<h1>UserInterests#save</h1>
<p>Find me in app/views/user_interests/save.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user, :url => update_user_path(@user)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset class="MS-medium">
		<legend> <%= legend rescue '' %> </legend>
		<div class="row UF-member">
    <%= image_tag(@user.avatar.url(:thumb), :class => "UF-profile-image span") %>
    </div>
		<%= f.label :name %>
		<%= f.text_field :name, :autofocus => true %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :location_country %>
		<div id="user_location_country"></div>

		<%= f.label :location_city %>
		<%= f.text_field :location_city %>
		<% if current_user.id == @user.id and action_name.include? "edit" %>
			<%= f.file_field :avatar, :class => "u-avatar" %>
    	<%= f.submit "Save", :class => "btn display-block" %>
		<% end %>
	</fieldset>
<% end %>


<script>
 $(function() {
    $("#user_location_country" ).magicSuggest({
        id: 'user_location_country',
        name: 'user[location_country]',
			  allowFreeEntries: false,
        data: "<%=COUNTRIES%>",
        value: '["<%=@user.location_country%>"]',
				maxDropHeightinteger: 120,
				maxSelection: 1
    });
  });
</script>

app/views/users/edit.html.erb
<%= render :partial => "form", :locals => { :legend => "Editing user profile" } %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% unless @users.blank? %>
<h1 class="UF-heading span10">Listing members</h1>
<div class="span10">
	<% @users.each do |user| %>
		<div class="row UF-member">
		<%= link_to user_path(user) do %>
			<%= image_tag(user.avatar.url(:thumb), :class => "UF-profile-image span") %>
			<div class="span3">
				<span class="UB-name"><%= user.name.capitalize %></span> <br/>
				<span class="UB-email"><%= user.email %></span>
			</div>
			<div class="span5">
				<% if user.interests.present? %>
					<h5><%=user.name%> is interested in </h5>
					<% user.interests.each_with_index do |ui, i| %>
						<span class="<%= i%2 == 1 ? 'odd' : 'even' %>"><%= " #{ui.name}" %></span>
					<% end %>
				<% else %>
					<h5><%=user.name.capitalize%> is not having any interest</h5>
				<% end %>
			</div>
		<% end %>
		</div>
		<%#= user.inspect %>
	<% end %>
</div>
<% end %>

app/views/users/new.html.erb
<%= render 'form', :locals => { :legend => "New user" } %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= render :partial => "form", :locals => { :legend => "User profile" } %>
<%= link_to 'Edit', edit_user_path(@user) if @user.id == current_user.id%>
<%= link_to 'Back', users_path %>